import { fontFamily } from 'tailwindcss/defaultTheme';
import { OptionalConfig } from 'tailwindcss/types/config';

import baseTailwindConfig from './theme/base-tailwind.config';

const config: Partial<OptionalConfig> = {
  presets: [baseTailwindConfig],
  theme: {
    extend: {
      colors: {
        'elevation-background': '#ffffff',
        'elevation-surface-1': '#f9fafb',
        'elevation-outline-1': '#e5e7eb',
        'elevation-outline-2': '#d1d5db',
        'interactive-primary-on': '#ffffff',
        'interactive-primary-idle': '#2b51d4',
        'interactive-primary-hover': '#477fea',
        'interactive-primary-disabled': '#9ac2f6',
        'interactive-primary-focus': '#6aa1f0',
        'interactive-secondary-on': '#ffffff',
        'interactive-secondary-idle': '#111827',
        'interactive-secondary-hover': '#374151',
        'interactive-secondary-disabled': '#9ca3af',
        'interactive-secondary-focus': '#6aa1f0',
        'interactive-outlined-on': '#111827',
        'interactive-outlined-idle': '#374151',
        'interactive-outlined-hover': '#2b51d4',
        'interactive-outlined-disabled': '#9ca3af',
        'interactive-outlined-focus': '#6aa1f0',
        'interactive-text-hover': '#6aa1f0',
        'interactive-text-disabled': '#6b7280',
        'interactive-text-focus': '#6aa1f0',
        'text-default-primary': '#111827',
        'text-default-secondary': '#374151',
        'text-inverted-primary': '#f3f4f6',
        'text-inverted-secondary': '#e5e7eb',
        'info-success': '#16a34a',
        'info-success-outline': '#4ade81',
        'info-error': '#d43f2b',
        'info-error-outline': '#e85e4b',
        'info-warning': '#f5880b',
        'info-warning-outline': '#fb9724',
        'interactive-text-on-bg-2': '#2b51d4',
        'interactive-text-on-bg': '#1f2937',
        'text-default-tertiary': '#6b7280',
        'text-inverted-tertiary': '#d1d5db',
        'interactive-primary-pressed': '#6aa1f0',
        'interactive-secondary-pressed': '#6b7280',
        'interactive-outlined-pressed': '#477fea',
        'interactive-text-pressed': '#9ac2f6',
        'interactive-outlined-on-toggled': '#ffffff',
        'interactive-outlined-toggled': '#111827',
        'interactive-icon-idle': '#374151',
        'interactive-icon-toggled': '#2b51d4',
        'interactive-icon-hover': '#477fea',
        'interactive-icon-pressed': '#6aa1f0',
        'interactive-icon-disabled': '#6b7280',
        'interactive-icon-focus': '#6aa1f0',
        'interactive-icon-on': '#ffffff',
        'elevation-surface-2': '#f3f4f6',
        'interactive-tertiary-on': '#4b5563',
        'interactive-tertiary-idle': '#e5e7eb',
        'interactive-tertiary-hover': '#d1d5db',
        'interactive-tertiary-pressed': '#9ca3af',
        'interactive-tertiary-on-disabled': '#9ca3af',
        'interactive-tertiary-focus': '#6aa1f0',
        'interactive-tertiary-toggled': '#6b7280',
        'interactive-text-on-inverted': '#ffffff',
        'interactive-tertiary-on-toggled': '#ffffff',
      },
      borderRadius: {
        none: '0rem',
        '2xs': '0.125rem',
        xs: '0.25rem',
        s: '0.375rem',
        sm: '0.5rem',
        ml: '0.75rem',
        xl: '1rem',
        '4xl': '1.5rem',
        full: '624.9375rem',
        '5xl': '1.75rem',
        '6xl': '2rem',
        m: '0.625rem',
        l: '0.875rem',
        '2xl': '1.125rem',
        '3xl': '1.25rem',
        'button-rounding': '0.375rem',
        'input-rounding': '0.375rem',
        'focus-rounding': '0.5rem',
      },
      maxWidth: {
        0: '0rem',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        18: '4.5rem',
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
        36: '9rem',
        40: '10rem',
        44: '11rem',
        48: '12rem',
        52: '13rem',
        56: '14rem',
        60: '15rem',
        64: '16rem',
        72: '18rem',
        80: '20rem',
        96: '24rem',
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
        '2xs': '16rem',
        '3xs': '12rem',
        '3-5xs': '9.75rem',
        '4xs': '8rem',
        '4-5xs': '7rem',
        '5-5xs': '4.75rem',
        '5xs': '6rem',
        px: '0.0625rem',
        '0-5': '0.125rem',
        '1-5': '0.375rem',
        '2-5': '0.625rem',
        '3-5': '0.875rem',
        'height-s': '0.625rem',
        'height-m': '1rem',
        'height-l': '1.25rem',
        'height-xs': '0.125rem',
        'icon-to-label-spacing': '0.25rem',
        'input-side-spacing': '0.75rem',
      },
      spacing: {
        0: '0rem',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        18: '4.5rem',
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
        36: '9rem',
        40: '10rem',
        44: '11rem',
        48: '12rem',
        52: '13rem',
        56: '14rem',
        60: '15rem',
        64: '16rem',
        72: '18rem',
        80: '20rem',
        96: '24rem',
        px: '0.0625rem',
        '0-5': '0.125rem',
        '1-5': '0.375rem',
        '2-5': '0.625rem',
        '3-5': '0.875rem',
        'height-s': '0.625rem',
        'height-m': '1rem',
        'height-l': '1.25rem',
        'height-xs': '0.125rem',
        'icon-to-label-spacing': '0.25rem',
        'input-side-spacing': '0.75rem',
      },
      boxShadow: {
        1: '0px 1px 2px 0px rgba(0, 0, 0, 0.05)',
        2: '0px 1px 3px 0px rgba(0, 0, 0, 0.10), 0px 1px 2px 0px rgba(0, 0, 0, 0.06)',
        3: '0px 4px 6px -1px rgba(0, 0, 0, 0.10), 0px 2px 4px -1px rgba(0, 0, 0, 0.06)',
        4: '0px 10px 15px -3px rgba(0, 0, 0, 0.10), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)',
        5: '0px 20px 25px -5px rgba(0, 0, 0, 0.10), 0px 10px 10px -5px rgba(0, 0, 0, 0.04)',
        6: '0px 25px 50px -12px rgba(0, 0, 0, 0.25)',
        inner: '0px 2px 4px 0px rgba(0, 0, 0, 0.06) inset',
      },
      blur: {
        0: '0px',
        1: '2px',
        2: '4px',
        3: '6px',
        4: '8px',
        5: '12px',
        6: '20px',
        7: '32px',
      },
      backdropBlur: {
        1: '2px',
        2: '4px',
        3: '6px',
        4: '8px',
        5: '12px',
        6: '20px',
        7: '32px',
      },
      fontSize: {
        'desktop-headline-1': [
          '3.5rem',
          {
            lineHeight: '1.2857',
            letterSpacing: '0em',
          },
        ],
        'desktop-title-1': [
          '3rem',
          {
            lineHeight: '1.25',
            letterSpacing: '0em',
          },
        ],
        'desktop-title-2': [
          '2rem',
          {
            lineHeight: '1.3125',
            letterSpacing: '0em',
          },
        ],
        'desktop-title-3': [
          '1.75rem',
          {
            lineHeight: '1.3571',
            letterSpacing: '0em',
          },
        ],
        'desktop-title-30': [
          '1.75rem',
          {
            lineHeight: '1.3571',
            letterSpacing: '0em',
          },
        ],
        'desktop-title-4': [
          '1.375rem',
          {
            lineHeight: '1.2727',
            letterSpacing: '0em',
          },
        ],
        'desktop-title-5': [
          '1.125rem',
          {
            lineHeight: '1.4444',
            letterSpacing: '0em',
          },
        ],
        'desktop-title-6': [
          '1rem',
          {
            lineHeight: '1.5',
            letterSpacing: '0em',
          },
        ],
        'mobile-headline-1': [
          '2rem',
          {
            lineHeight: '1.1875',
            letterSpacing: '0em',
          },
        ],
        'mobile-title-1': [
          '1.75rem',
          {
            lineHeight: '1.2857',
            letterSpacing: '0em',
          },
        ],
        'mobile-title-2': [
          '1.5rem',
          {
            lineHeight: '1.3333',
            letterSpacing: '0em',
          },
        ],
        'mobile-title-3': [
          '1.125rem',
          {
            lineHeight: '1.4444',
            letterSpacing: '0em',
          },
        ],
        'mobile-title-4': [
          '1rem',
          {
            lineHeight: '1.5',
            letterSpacing: '0em',
          },
        ],
        'mobile-title-5': [
          '0.875rem',
          {
            lineHeight: '1.2857',
            letterSpacing: '0em',
          },
        ],
        'mobile-title-6': [
          '0.875rem',
          {
            lineHeight: '1.2857',
            letterSpacing: '0em',
          },
        ],
        'desktop-body-1': [
          '1.25rem',
          {
            lineHeight: '1.8',
            letterSpacing: '-0.002em',
          },
        ],
        'desktop-body-2': [
          '1.125rem',
          {
            lineHeight: '1.7778',
            letterSpacing: '-0.0018em',
          },
        ],
        'desktop-body-3': [
          '1rem',
          {
            lineHeight: '1.75',
            letterSpacing: '-0.0016em',
          },
        ],
        'desktop-body-4': [
          '0.875rem',
          {
            lineHeight: '1.7143',
            letterSpacing: '-0.0014em',
          },
        ],
        'mobile-body-1': [
          '1.125rem',
          {
            lineHeight: '1.5556',
            letterSpacing: '-0.0018em',
          },
        ],
        'mobile-body-2': [
          '1rem',
          {
            lineHeight: '1.75',
            letterSpacing: '-0.0016em',
          },
        ],
        'mobile-body-3': [
          '0.9375rem',
          {
            lineHeight: '1.7333',
            letterSpacing: '-0.0015em',
          },
        ],
        'mobile-body-4': [
          '0.875rem',
          {
            lineHeight: '1.7143',
            letterSpacing: '-0.0014em',
          },
        ],
        'label-1': [
          '1rem',
          {
            lineHeight: '1.5',
            letterSpacing: '-0.0016em',
          },
        ],
        'label-2': [
          '0.875rem',
          {
            lineHeight: '1.7143',
            letterSpacing: '-0.0014em',
          },
        ],
        'label-3': [
          '0.75rem',
          {
            lineHeight: '1.3333',
            letterSpacing: '-0.0012em',
          },
        ],
      },
      fontFamily: {
        syne: ['var(--font-syne)', ...fontFamily.sans],
        inter: ['var(--font-inter)', ...fontFamily.sans],
      },
      fontWeight: {
        'headings-default': '500',
        'headings-prominent-1': '600',
        'headings-prominent-10': '600',
        'body-default': '400',
        'body-prominent-1': '500',
        'body-prominent-2': '600',
        'labels-default': '500',
        'labels-prominent-1': '600',
      },
      backgroundImage: {},
    },
  },
};

export default config;
